gems:
  - jekyll-multiple-languages-plugin

title: The Guide To The Fediverse
email: fed@ialis.me
description: "A guide to the fediverse, an open, free and decentralized social microblogging network and its different versions (Mastodon, GNUSocial, ...)."
baseurl: ""
url: "https://fed.ialis.me"

# Build settings
markdown: kramdown

permalink: "/news/:year/:month/:day/:title.html"

# I18n

languages: ["en", "fr"]
directory_languages: ["en", "fr", "es", "de", "nl", "he", "jp"]
exclude_from_localization: ["assets"]

